# First print your name in the cell below then save this file. (or something nice about your instructor)

In [7]:
# In this cell print your name 
print("Simon Zheng")

Simon Zheng

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [1]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
# Load data here
df = pd.read_csv('../data/listings.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [30]:
# 1. How many listings are there with a price less than 100? 
under100 = df['price'] < 100
under100_value = df[under100].copy()
under100_value.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344

In [8]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
brooklyn = df['neighbourhood_group'] == 'Brooklyn'
df_bk = df[brooklyn].copy()
df_bk.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0

In [21]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
brooklynLess100 = df_bk['price'] < 100
df_bk_100 = df_bk[brooklynLess100].copy()
df_bk_100.neighbourhood_group.value_counts()

neighbourhood_group
Brooklyn    10473
Name: count, dtype: int64

In [26]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
name = ['Michael' , 'David' , 'John' , 'Daniel']
condition = df.host_name.isin(name)

df[condition]['host_name'].value_counts()

host_name
Michael    387
David      348
John       270
Daniel     253
Name: count, dtype: int64

In [35]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
c1 = df['neighbourhood'] == 'Williamsburg'
df['adjusted_price'] = np.where(c1, df['price'] + 100, df['price'])
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,175
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,60
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,175
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,65

In [39]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
room_types = df['room_type'].value_counts()
room_types_percent = df['room_type'].value_counts(normalize=True) * 100
room_types_percent

room_type
Entire home/apt    51.578653
Private room       45.444581
Shared room         2.121349
Hotel room          0.855417
Name: proportion, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [41]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
nb_groups = df.groupby('neighbourhood_group')
nb_counts = nb_groups.size()
nb_counts

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [47]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
nb_price = df.groupby('neighbourhood_group')
nb_price['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [46]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
rm_type = df.groupby('room_type')
rm_type['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [48]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
nb_p = df.groupby('neighbourhood_group')
nb_p['price'].agg( ['min', 'max'] )

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [49]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

rm_nb = df.groupby(['room_type', 'neighbourhood_group'])
rm_nb['price'].mean()

room_type        neighbourhood_group
Entire home/apt  Bronx                  138.004819
                 Brooklyn               171.587687
                 Manhattan              231.335572
                 Queens                 150.168900
                 Staten Island          151.720930
Hotel room       Brooklyn               147.300000
                 Manhattan              292.515670
                 Queens                 139.058824
Private room     Bronx                   68.419668
                 Brooklyn                71.291189
                 Manhattan              128.277069
                 Queens                  69.972564
                 Staten Island           70.312883
Shared room      Bronx                   66.391304
                 Brooklyn                57.870091
                 Manhattan              111.735084
                 Queens                  89.891892
                 Staten Island           46.000000
Name: price, dtype: float64

In [50]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

rm_nb_agg = df.groupby(['room_type', 'neighbourhood_group'])
rm_nb_agg['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

                                     count  min    max        mean  median  \
room_type       neighbourhood_group
Entire home/apt Bronx                  415   25   1404  138.004819   103.0
                Brooklyn              9112   20  10000  171.587687   135.0
                Manhattan            12209    0  10000  231.335572   165.0
                Queens                2090   10  10000  150.168900   115.0
                Staten Island          172   39   1200  151.720930   111.0
Hotel room      Brooklyn                30    0    399  147.300000   129.0
                Manhattan              351    0   2211  292.515670   210.0
                Queens                  17    0    249  139.058824   149.0
Private room    Bronx                  722   16    700   68.419668    55.0
                Brooklyn              9159   10   2500   71.291189    60.0
                Manhattan             7601   10  10000  128.277069    80.0
                Queens                3499   18   9000   69.972564    55.0
                Staten Island          163   20    800   70.312883    55.0
Shared room     Bronx                   46   20    800   66.391304    44.0
                Brooklyn               331   15   1500   57.870091    36.0
                Manhattan              419   10  10000  111.735084    60.0
                Queens                 185   14   3000   89.891892    40.0
                Staten Island            6   19     82   46.000000    38.0

                                            std
room_type       neighbourhood_group
Entire home/apt Bronx                126.032106
                Brooklyn             236.732843
                Manhattan            410.306439
                Queens               252.606739
                Staten Island        147.518392
Hotel room      Brooklyn              91.153206
                Manhattan            315.924085
                Queens                50.743806
Private room    Bronx                 57.337866
                Brooklyn              69.023165
                Manhattan            448.677306
                Queens               163.814468
                Staten Island         70.759593
Shared room     Bronx                114.442703
                Brooklyn              92.217618
                Manhattan            502.728868
                Queens               275.675158
                Staten Island         28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [62]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_prices = pd.read_csv('../data/prices.csv')
df_n_listings = pd.read_csv('../data/n_listings.csv', sep=';')

df_prices.head()

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

In [64]:
# 2. Do join that keeps all the records for each table.
data = pd.merge(
    df_prices,
    df_n_listings,
    on='neighbourhood_group', 
    how='outer'
)
data.head()

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN

In [65]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
data.to_csv('../data/joined.csv', index=False)

In [67]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
df_joined = pd.read_csv('../data/joined.csv')
df_joined.head()

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

In [ ]:
# !pip install pandas-profiling

import pandas as pd
from pandas_profiling import ProfileReport

df = pd.read_csv('../data/listings.csv')
profile = ProfileReport(df, explorative=True)
profile.to_file("../data/listings_profile.html")

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.13/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.13/u/import-error

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [76]:
import pandas as pd

df = pd.read_csv('../data/grammys.csv')

# 1. Album of the Year in 2016
result1 = df[
    (df['year'] == 2016) &
    (df['category'] == 'Album of the Year') &
    (df['winner'] == True)
]

print(result1[['year', 'category', 'nominee', 'workers']])

# 2. Best Rap Album in 2009
result2 = df[
    (df['year'] == 2009) &
    (df['category'] == 'Best Rap Album') &
    (df['winner'] == True)
]
print(result2[['year', 'category', 'nominee', 'workers']])

# 3. Kendrick Lamar nominations and wins
k = df[df['workers'].str.contains('Kendrick Lamar', na=False, case=False)]

print('Total nominations:', len(k))
print('Total wins:', k['winner'].sum())
print(k[['year', 'category', 'nominee', 'winner']].head(20))

      year           category nominee  \
5505  2016  Album of the Year   1989.

                                                workers
5505  Taylor Swift (artist/producer), Jack Antonoff ...
      year        category         nominee     workers
4396  2009  Best Rap Album  Tha Carter III  Lil' Wayne
Total nominations: 20
Total wins: 11
      year                     category  \
5269  2014               Best Rap Album
5272  2014         Best Rap Performance
5448  2015         Best Rap Performance
5451  2015                Best Rap Song
5507  2016            Album of the Year
5575  2016             Best Music Video
5596  2016               Best Rap Album
5599  2016         Best Rap Performance
5602  2016                Best Rap Song
5604  2016                Best Rap Song
5605  2016  Best Rap/Sung Collaboration
5654  2017            Album of the Year
6000  2018               Best Rap Album
6003  2018         Best Rap Performance
6006  2018                Best Rap Song
6009  2018    Best Rap/Sung Performance
6087  2019            Album of the Year
6248  2019                Best Rap Song
6252  2019    Best Rap/Sung Performance
6317  2019           Record of the Year

                                                nominee  winner
5269                            Good Kid, M.A.A.D City.   False
5272                            Swimming Pools (Drank).   False
5448                                                 i.    True
5451                                                 i.    True
5507                               To Pimp a Butterfly.   False
5575                            Taylor Swift: Bad Blood    True
5596                               To Pimp a Butterfly.    True
5599                                           Alright.    True
5602                                           Alright.    True
5604                                           All Day.   False
5605                                       These Walls.    True
5654                                           Lemonade   False
6000                                               Damn    True
6003                                            HUMBLE.    True
6006                                             Humble    True
6009                                           LOYALTY.    True
6087  Black Panther: The Album, Music from and Inspi...   False
6248                                     Win (Jay Rock)   False
6252                                      All the Stars   False
6317                                      All the Stars   False

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

In [ ]:
import pandas as pd

# Example if the raw data has no header
raw = pd.read_csv('your_game_log_file.csv', header=None)

cols = {
    0: 'date',
    1: 'game_number',
    2: 'day',
    3: 'visitor_team',
    4: 'visitor_runs',
    5: 'home_team',
    6: 'home_runs',
    # ... add the rest from the Retrosheet column list
}

raw = raw.rename(columns=cols)
raw.head()

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.

..

In [ ]:
import pandas as pd
from pathlib import Path

folder = Path('../data')   # or wherever your game log files live
all_files = sorted(folder.glob('*.csv'))

df_list = []
for f in all_files:
    temp = pd.read_csv(f, header=None)
    # rename columns here if needed
    df_list.append(temp)

combined = pd.concat(df_list, ignore_index=True)
combined.to_csv('../data/all_game_logs_2020_2024.csv', index=False)